---
title: "Project m3"
author: "Xinyi Wang"
date: "2023-05-06"
---

```{r setup, include=FALSE, message=FALSE}
library(shinyWidgets)
library(rsconnect)
library(plotly)
library(DT)
library(shiny)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(patchwork)
library(rstatix)
library(ggpubr)
library(RColorBrewer)
theme_set(theme_bw())
```


#Data preparation and data cleaning
```{r,message=FALSE, include=FALSE}
data <- read.csv("https://github.com/yicenyang/stat436/raw/main/heart.csv") %>%
  drop_na() %>%
  mutate(sex = ifelse(sex == 1, "Male", "Female"),
         target = ifelse(target == 1, "Disease", "No Disease")) %>% 
  rename("heart.rate" = "thalach",
         "blood.pressure" = "trestbps",
         "cholesterol" = "chol")
data$index <- 1:nrow(data)
data
```


#Logistic regression
```{r}
data1 <- read.csv("https://github.com/yicenyang/stat436/raw/main/heart.csv") %>%
  drop_na()%>% 
  rename("heart.rate" = "thalach",
         "blood.pressure" = "trestbps",
         "cholesterol" = "chol")
model = glm(target ~ heart.rate + blood.pressure + cholesterol, data = data1, family = binomial(link = "logit"))
summary(model)
```


#Data overview

#Density plots
```{r}
 d1 = ggplot(data, aes(x = blood.pressure)) +
     geom_density(aes(fill = as.factor(target)), alpha = 0.5)+
  labs(fill = "Disease Status", shape = "sex", x = "blood pressure")+
   scale_y_continuous(expand = c(0,0,0.001,0.001))
 d2 = ggplot(data,aes(x = cholesterol))+
  geom_density(aes(fill=as.factor(target)), alpha = 0.5)+
  labs(fill = "Disease Status", shape = "sex", x = "cholesterol")+
   scale_y_continuous(expand = c(0,0,0.001,0.001))
 d3 = ggplot(data,aes(x = heart.rate))+
  geom_density(aes(fill=as.factor(target)), alpha = 0.5)+
  labs(fill = "Disease Status", shape = "sex", x = "heart rate")+
   scale_y_continuous(expand = c(0,0,0.001,0.001))
(d1/d2/d3) +
  plot_layout(guides = "collect") +
  plot_annotation(theme = theme(legend.position = "right", 
                                legend.title = element_text(size = 10))) 
```

#scatterplots
```{r, fig.width = 8, fig.height = 6}
p <- list()

data5 = data1 %>% filter(target == 1)
data6 = data1 %>% filter(target == 0)

p[["scatter"]]  <- ggplot(data, aes(x = age, y = heart.rate)) +
  geom_point(aes(col = as.factor(target), shape = as.factor(sex))) +
  labs(fill = "Disease Status") +
  stat_smooth(data = data5, method = "lm", se = FALSE, col = "red", size = 1.5) +
  stat_smooth(data = data6, method = "lm", se = FALSE, col = "blue", size = 1.5) +
  theme(legend.text = element_text(size = 15)) +
  labs(color = "Disease Status", y = "heart rate",shape = "sex")


 p[["scatter2"]] <- ggplot(data, aes(x = age,y = blood.pressure))+
  geom_point(aes(col=as.factor(target),shape = as.factor(sex))) +
   labs(fill = "Disease Status") +
   stat_smooth(data = data5, aes(x = age, y = blood.pressure), method = "lm", se = FALSE, col = "red", size = 1.5)+
  stat_smooth(data = data6, method = "lm", se = FALSE, col = "blue", size = 1.5) +
   theme(legend.text = element_text(size = 15))+ 
   labs(color = "Disease Status", y = "blood pressure",shape = "sex")
 
 p[["scatter3"]] <- ggplot(data, aes(x = age,y = cholesterol))+
  geom_point(aes(col=as.factor(target),shape = as.factor(sex))) + 
   labs(fill = "Disease Status") + 
   stat_smooth(data = data5, aes(x = age, y = cholesterol), method = "lm", se = FALSE, col = "red", size = 1.5)+
  stat_smooth(data = data6, method = "lm", se = FALSE, col = "blue", size = 1.5) +
   theme(legend.text = element_text(size = 15)) + 
   labs(color = "Disease Status", y = "cholesterol",shape = "sex")

  p[["scatter"]]/p[["scatter2"]]/p[["scatter3"]] +
    plot_layout(guides = "collect") &
   plot_annotation(theme = theme(legend.position = "right", 
                                 legend.title = element_text(size = 15)))
```

#grouping age into 4 groups
```{r}
data = read.csv("https://github.com/yicenyang/stat436/raw/main/heart.csv")%>% 
  rename("heart.rate" = "thalach",
         "blood.pressure" = "trestbps",
         "cholesterol" = "chol")
min(data$age)
max(data$age)
heart4 <- data %>% 
  mutate(sex = ifelse(sex == 1, "Male", "Female")) %>% 
  mutate(target = ifelse(target == 1, "Disease", "No Disease"),age_range = case_when(20 < age & age <= 40 ~ "20-40",
                                 41<=age& age<=50 ~ "40-50",
                                 51<=age& age<=60 ~ "50-60",
                                 61<=age ~ "over 60",
                                 )) 

heart4 = heart4 %>%
  mutate(row_index = row_number())
data77 = read.csv("https://github.com/yicenyang/stat436/raw/main/heart.csv")%>% drop_na()
```


#function generation
```{r}
data_table <- function(data, selected_) {
  data %>%
    filter(selected_) %>%
    select(age,sex,blood.pressure,cholesterol,heart.rate,target)
}
data_mean <- function(data, selected_) {
  data %>%
    filter(selected_) %>%
    summarise(mean=mean(target))%>%
    pull()
}

counts <- list(
  "blood.pressure" = count(data, blood.pressure),
  "cholesterol " = count(data, cholesterol),
  "heart.rate" = count(data, heart.rate)
)

bar_plot <- function(sub_flights, v, width = 5) {
  ggplot(counts[[v]], aes(.data[[v]], n, fill = age_range)) +
    geom_col(data = sub_flights, stat = "identity", width = width, aes(fill = age_range)) +
    scale_fill_manual(values = c("20-40" = "red", "40-50" = "black", "50-60" = "purple", "over 60" = "pink"))
}


plot_overlay <- function(selected_, v, width = 5) {
  data %>%
    filter(selected_) %>%
    add_age_range() %>% # Add this line to include age_range info
    count(.data[[v]], age_range) %>%
    bar_plot(v, width)
}

scatterplot <- function(data, selected_) {
  data %>%
    mutate(selected_ = selected_) %>%
    ggplot() +
    geom_point(aes(cholesterol, heart.rate, col = as.factor(target), shape = as.factor(sex), alpha = as.numeric(selected_))) +
    scale_alpha(range = c(0.05, 0.6)) +
    labs(shape = "sex", alpha = "Selected", col = "Disease Status")
}


reset_selection <- function(x, brush) {
  xvar <- str_match(brush$mapping$x, "blood.pressure|cholesterol|age")[1]
  brushedPoints(x, brush, allRows = TRUE, xvar = xvar)$selected_
}
add_age_range <- function(data) {
  data %>%
    mutate(age_range = case_when( 20 < age & age <= 40 ~ "20-40",
                                  41 <= age & age <= 50 ~ "40-50",
                                  51 <= age & age <= 60 ~ "50-60",
                                  61 <= age ~ "over 60",
    )) 
}
```


#main code of shiny app
```{r, fig.width = 18, fig.height = 16}
ui1 <- fluidPage(
  titlePanel("Risk factors of heart disease"),
  setBackgroundColor(
    color = c("lightyellow","mistyrose"),
    gradient = "linear",
    direction = "bottom"
  ),
  fluidRow(
    column(6,
      p(strong("Description: "),"This shiny displays histograms to display distribution of age, heart rate, blood pressure, and cholesterol, as well as a scatterplot to show correlation of cholesterol and heart rate and the table to show detailed information. By selecting different age range and brushing different subsets, the new outputs would be re-generated."),
      br(),
      h4("Selected data information:"),
      tags$ul(
        tags$b(textOutput("info")),
        tags$b(textOutput("average_heart_disease_rate"))
      ),
      selectInput("age","Select age range:",choices = sort(unique(heart4$age_range)), multiple = TRUE),
      plotOutput("histogram_blood.pressure", brush = brushOpts("plot_brush", direction = "x"), height = 200),
      plotOutput("histogram_cholesterol", brush = brushOpts("plot_brush", direction = "x"), height = 200),
      plotOutput("histogram_heartrate", brush = brushOpts("plot_brush", direction = "x"), height = 200)
    ),
    column(6,
      plotOutput("scatterplot", brush = "plot_brush"),
      dataTableOutput("table")
    )
  )
)

server1 <- function(input, output) {
  selected <- reactiveVal(rep(TRUE, nrow(heart4)))

  # Create age_range variable as a reactive function
  age_filtered_data <- reactive({
    req(input$age)
    heart4 %>%
      filter(age_range %in% input$age)
  })

  observeEvent(
    input$plot_brush,
    selected(reset_selection(heart4, input$plot_brush))
  )

  # Update the observeEvent for input$age
  observeEvent(
    input$age,
    {
      if (is.null(input$age)) {
        selected(rep(TRUE, nrow(heart4)))
      } else {
        age_filtered_rows <- age_filtered_data()$row_index
        selected_age <- rep(FALSE, nrow(heart4))
        selected_age[age_filtered_rows] <- TRUE
        selected(selected_age)
      }
    }
  )
  output$histogram_blood.pressure <- renderPlot({
  plot_overlay(selected(),"blood.pressure",1) + 
      ggtitle("Distribution of blood.pressure/cholesterol/heart.rate")
})
  output$histogram_cholesterol  <- renderPlot(
    plot_overlay(selected(),"cholesterol",5))
  output$histogram_heartrate <- renderPlot(
    plot_overlay(selected(),"heart.rate",5)+
    xlab("heart rate"))
  output$scatterplot <- renderPlot({
    scatterplot(heart4, selected())+
      ggtitle("Correlation between heart rate and cholesterol")
})
  output$table <- renderDataTable(data_table(heart4, selected()))
  output$average_heart_disease_rate <- renderText({
    paste0("Average heart disease rate for selected data: ", data_mean(data77, selected()))
  })
  output$info = renderText({
    paste0("Selected data count: ", nrow(filter(heart4, selected())))
  })
}

app1 <- shinyApp(ui = ui1, server = server1)
```



#T test and boxplots
```{r}
#generate function
stat.test <- heart4 %>%
  group_by(age_range) %>%
  t_test(cholesterol~ target,paired = FALSE) %>%
  adjust_pvalue() %>%
  add_significance("p.adj")
stat.test
```

```{r}
theme_set(theme_bw())
stat =function(x,y){
  fm <- as.formula(paste(x, y , sep = "~"))
  heart4%>%
  group_by(age_range) %>%
  t_test(fm,paired = FALSE) %>%
  adjust_pvalue() %>%
  add_significance("p.adj")%>%
    add_xy_position(x = "target")%>%
   mutate(custom.label = case_when(
      p <= 0.01 ~ "significant",
      p > 0.01 & p <= 0.1 ~ as.character(round(p, 3)),
      p > 0.1 ~ "not significant"
    ))
}
```

```{r}
cholesterol  = stat(x = "cholesterol", y = "target")
blood.pressure = stat(x = "blood.pressure", y = "target")
heart.rate = stat(x = "heart.rate", y = "target")
```

```{r}
bp1 = function(x){
  ggboxplot(heart4, x = "target", y = x,fill = "target", palette = "jco",facet.by = "age_range")+
    labs(fill = "Disease Status")+theme_bw()
}
```

```{r,fig.width = 11}
p1 = bp1("cholesterol")+ 
  stat_pvalue_manual(cholesterol, label = "custom.label") +
  xlab("Disease Status")+
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))


p2 = bp1("blood.pressure")+ 
  stat_pvalue_manual(blood.pressure, label = "custom.label") +
  xlab("Disease Status")+
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))

p3 = bp1("heart.rate")+ 
  stat_pvalue_manual(heart.rate, label = "custom.label") +
  xlab("Disease Status")+
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))

p1+ p2+ p3+ plot_layout(guide = "collect")
```


#usmap shiny
```{r}
# prepare data
data10 = read_csv("https://uwmadison.box.com/shared/static/8cxdb08bj3jfcicda06h0n0tg5l50kn7.csv")
data20 <- data10 %>%
  rename(Gender = Stratification1,
         Race = Stratification2)

us_states <- map_data("state")
state = read.csv("https://uwmadison.box.com/shared/static/59noryjk6oac0zlt42uhd1ktfmh9la9l.csv")
state$City = tolower(state$City)
```

#function generation
```{r}
plot_choropleth <- function(filtered_data) {
  state_data <- filtered_data %>%
    group_by(LocationAbbr) %>%
    summarize(value = round(mean(Data_Value, na.rm = TRUE),0))

  merged_data <- inner_join(state_data , state, by = c("LocationAbbr" = "State"))
  merged_data2 <- inner_join(us_states,merged_data, by = c("region" = "City"))

  ggplot(data = merged_data2, aes(x = long, y = lat, group = group, fill = value, text = paste("State:", LocationAbbr, "<br>Value:", value))) +
    geom_polygon(color = "black", size = 0.2) +
    scale_fill_viridis_c(option = "viridis", na.value = "gray90", 
                         guide = guide_colorbar(title = "Average Death")) + 
    labs(title = "State Average Death per 100,000 by CVD") +
    theme_minimal() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_blank(),
          legend.position = "right")
}
```



#main code of usmap
```{r,warning = False}
ui2 <- fluidPage(
  titlePanel("Choropleth Map by Gender and Race"),
  setBackgroundColor(
    color = c("pink", "lightblue"),
    gradient = "linear",
    direction = "bottom"
  ),
  p(strong("Description: "),
    "This interactive choropleth map displays the average death per 100,000 by cardiovascular disease (CVD) in the United States, based on gender and race. Use the sidebar options to select gender and race categories to filter the data displayed on the map. Click on a state to see the corresponding average death per 100,000 for the selected category."),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("gender", label = "Select Gender",
                  choices = c("Overall", "Male", "Female")),
      selectInput("race", label = "Select Race",
                  choices = c("Overall", "White", "Black", "Hispanic","Asian and Pacific Islander", "American Indian and Alaskan Native"))
    ),
    
    mainPanel(
      plotlyOutput("choroplethMap"),
      verbatimTextOutput("info")
    )
  )
)
server2 <- function(input, output, session) {
  output$choroplethMap <- renderPlotly({
    # Filter data based on user selection
    filtered_data <- data20 %>%
      filter(Gender == input$gender,
             Race == input$race)
    
    choropleth_map <- plot_choropleth(filtered_data)

    ggplotly(choropleth_map, tooltip = "text") %>%
      layout(dragmode = "select")
  })

 observeEvent(event_data("plotly_click", source = "choroplethMap"), {
  click <- event_data("plotly_click", source = "choroplethMap")
  state_info <- strsplit(click[["text"]], "<br>")[[1]]
  state_abbr <- gsub("State: ", "", state_info[1])
  value <- gsub("Value: ", "", state_info[2])
  output$info <- renderText(paste("State:", state_abbr, " Value:", value))
 })
 }

app2 = shinyApp(ui2, server2)
```